worker_processes 1;
user nobody nogroup;
pid /tmp/nginx.pid;
error_log /tmp/nginx.error.log;
events {
  worker_connections 1024; # increase if you have lots of clients
  accept_mutex off; # set to 'on' if nginx worker_processes > 1
}
http {
  include mime.types;
  default_type application/octet-stream;
  access_log /tmp/nginx.access.log combined;
  sendfile off;
  upstream app_server {
    server unix:/tmp/gunicorn.sock fail_timeout=0;
  }
  
  server {
    # if no Host match, close the connection to prevent host spoofing
    listen 8081 default_server;
    return 444;
  }
  
  server {
    listen 80 default_server;
    server_name my.dns.com;
    return 301 https://my.dns.com$request_uri;
  }

  server {
    listen 443 ssl http2;
    server_name my.dns.com;

    ssl_certificate           /etc/ssl/certs/server.pem;
    ssl_certificate_key       /etc/ssl/certs/my-server.key.pem;
    ssl_session_cache  builtin:1000  shared:SSL:10m;
    ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    ssl_prefer_server_ciphers on;
    keepalive_timeout 5;
    underscores_in_headers on;

    location / {
        proxy_pass http://grafana:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
  }

# Loki Ingestion Proxy (Port 3100)
  server {
    listen 3100;
    
    # Critical: Allow large log batches from remote VMs
    client_max_body_size 100M; 

    location / {
        proxy_pass http://loki:3100;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;

    }
  }
}
